version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - run

jobs:
  run:
    macos:
      xcode: "9.4.1"
    environment: 
      HOMEBREW_DEVELOPER=1
      HOMEBREW_NO_AUTO_UPDATE=1
    steps:
      - checkout
      - restore_cache:
          key:
      - run: export PYTHONPATH=${PYTHONPATH}:${PWD}/python
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
      - run: export PATH="/usr/local/opt/ccache/libexec:$PATH"
      - run: source ci/travis/install.sh
      - run: export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
      - run: mv make/osx.mk config.mk
      - run: make -j 2
