version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - run

jobs:
  run:
    macos:
      xcode: "9.4.1"
    environment:
      TRAVIS_OS_NAME: osx
    steps:
      - checkout
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
            - cache
      - run:
          name: Build Script
          command: |
            export PYTHONPATH=${PYTHONPATH}:${PWD}/python
            HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache pkg-config            
            export PATH="/usr/local/opt/ccache/libexec:$PATH"
            source ci/travis/install.sh
            export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
            mv make/osx.mk config.mk
            make -j 2
      - save_cache:
          key: cache
          paths:
            - /Users/distiller/.ccache
            - /Users/distiller/.cache/pip
            - /Users/distiller/.mxnet
            - /Users/distiller/Library/Caches/Homebrew
