version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - run

jobs:
  run:
    macos:
      xcode: "9.4.1"
    environment: 
      HOMEBREW_DEVELOPER=1
      HOMEBREW_NO_AUTO_UPDATE=1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache
      - run:
          name: Before Install
          command: 
            export PYTHONPATH=${PYTHONPATH}:${PWD}/python
            git clone --recursive https://github.com/dmlc/xgboost.git
      - run: 
          name: Install
          command: | 
            HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
            export PATH="/usr/local/opt/ccache/libexec:$PATH"
            source ci/travis/install.sh
      - run: 
          name: Script
          command: |
            export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
            mv make/osx.mk config.mk
            echo $CURDIR
            make -j 2
      - save_cache:
          key: cache
          paths:
            - $HOME/.cache/pip
            - $HOME/.mxnet
            - $HOME/Library/Caches/Homebrew
            - $HOME/.ccache
