version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - run

jobs:
  run:
    macos:
      xcode: "9.4.1"
    environment:
      TRAVIS_OS_NAME: osx
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache
      - run:
          name: Before Install
          command: |
            echo "****** 1"
            git submodule update --init --recursive
            #export PYTHONPATH=${PYTHONPATH}:${PWD}/python
            #git clone --recursive https://github.com/dmlc/xgboost
            HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache pkg-config
            echo "****** 2"
            export PATH="/usr/local/opt/ccache/libexec:$PATH"
            echo "****** 3"
            source ci/travis/install.sh
            echo "****** 4"
            export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
            echo "****** 5"
            mv make/osx.mk config.mk            
            echo "****** 6"
            make -j 2
            echo "****** 7"
#       - run: 
#           name: Install
#           command: | 
#             HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
#             export PATH="/usr/local/opt/ccache/libexec:$PATH"
#             source ci/travis/install.sh
#       - run: 
#           name: Script
#           command: |
#             export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
#             mv make/osx.mk config.mk
#             echo $CURDIR
#             make -j 2
      - save_cache:
          key: cache
          paths:
            - /Users/distiller/.ccache
            - /Users/distiller/.cache/pip
            - /Users/distiller/.mxnet
            - /Users/distiller/Library/Caches/Homebrew
            
